name = "sub"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "23460e88ead340cea877d6a9d754677f"

[triggers]
crons = ["0 8 * * *"]

[vars]
ENVIRONMENT = "production"
